# Generated by Django 4.2.5 on 2023-09-30 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_alter_mailing_client_alter_message_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailer.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='mailing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailer.mailing'),
            preserve_default=False,
        ),
    ]
